include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    # 対応するパラメータのデフォルトと一致する引数を渡すことを禁止
    avoid_redundant_argument_values: false

    # 可能な場合は、定義済みの const 値を使用します
    use_named_constants: false

    # 対応するダブルリテラルではなく、intリテラルを使用してください
    prefer_int_literals: false

    # 条件式でのブールリテラルは避けてください
    avoid_bool_literals_in_conditional_expressions: false

    # 1行の文字数は80文字まで
    lines_longer_than_80_chars: false

    # プロパティを概念的に変更する操作には、セッターを使用します。
    # Riverpodの操作で不便の為、falseにしています
    use_setters_to_change_properties: false

    # デフォルトのケースはありません。
    # このプロジェクトにおいてデフォルトのケースが有用であるケースは存在する。
    no_default_cases: false

    # Staticメンバーのみを持つクラスを避ける
    # 大規模なプロジェクトでは、staticメンバーのみを持つクラスが有用な場合がある
    # Intellisenseが膨大になってしまうため、falseにしています
    avoid_classes_with_only_static_members: false

    # try-catch文でon句を必ず使用しなければならない
    # 厳密すぎるので、falseにしています
    avoid_catches_without_on_clauses: false

    # 最上位変数と静的変数の明らかな型注釈は省略します
    # このプロジェクトでは、型注釈を明示的に書くことで可読性を向上させるため、falseにしています
    omit_obvious_property_types: false

    # すべてのパラメーター・リストと引数リストには、末尾のコンマを使用します。
    require_trailing_commas: true

analyzer:
  errors:
    # Freezedを使用する際に発生するアノテーションエラーを無視
    # https://t.co/EhoXMGIunb
    invalid_annotation_target: ignore

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
# https://dart.dev/tools/linter-rules

# Dartチーム純正のルール
# include: package:flutter_lints/flutter.yaml

# このプロジェクトで使用しているpedantic_monoのルール
# https://pub.dev/packages/pedantic_mono
