name: flutter_learning
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  go_router: ^14.8.1
  google_generative_ai: ^0.4.6
  hooks_riverpod: ^2.6.1
  intl: ^0.19.0
  logger: ^2.5.0
  path: ^1.8.3
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.2
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.2
  go_router_builder: ^2.7.1
  json_serializable: ^6.9.0
  lints: ^5.1.1
  pedantic_mono: ^1.30.3
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

dependency_overrides:
  freezed_annotation: 3.0.0

flutter:
  generate: true # gen-l10n コマンドを有効化
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/OFL.txt
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Bold.otf
        - asset: assets/fonts/NotoSansJP-Regular.otf
